name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    
    - name: Install dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore --output ./output
  
    
    - name: Deploy
      shell: bash
      run: |
        apt-get install sshpass 
        sshpass -p 'pak123lahore' scp ./output ubuntu@3.83.101.195:~/var/www/program_build
      
