name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  IP_ADDRESS: '3.83.101.195'
  USERNAME: 'ubuntu'
  PASSWORD: 'pak123lahore'
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    
    - name: Install dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore --output ./output
  
    - name: SSH Deploy
      shell: bash
      run: |
        sudo apt-get install sshpass
        tar -cvf ./output.tar ./output/*
        sshpass -p ${{ env.PASSWORD }} scp ./output.tar ubuntu@3.83.101.195:/home/ubuntu/output.tar
        
    - name: SSH Deploy
      shell: bash
      run: |
        sshpass -p ${{ env.PASSWORD }} ssh ${{ env.USERNAME }}@${{ env.IP_ADDRESS }} "sudo systemctl stop hello"
        
    - name: SSH Deploy
      shell: bash
      run: |
        sshpass -p ${{ env.PASSWORD }} ssh ${{ env.USERNAME }}@${{ env.IP_ADDRESS }} "sudo rm -R '/var/www/project_output'"
        
    - name: SSH Deploy
      shell: bash
      run: |
        sshpass -p ${{ env.PASSWORD }} ssh ${{ env.USERNAME }}@${{ env.IP_ADDRESS }} "sudo cp -R '/home/ubuntu/output' '/var/www/project_output' "
        
    - name: SSH Deploy
      shell: bash
      run: |
        sshpass -p ${{ env.PASSWORD }} ssh ${{ env.USERNAME }}@${{ env.IP_ADDRESS }} "sudo rm -R '/home/ubuntu/output'"
        
    - name: SSH Deploy
      shell: bash
      run: |
        sshpass -p ${{ env.PASSWORD }} ssh ${{ env.USERNAME }}@${{ env.IP_ADDRESS }} "sudo systemctl start hello"   
          
        
