name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    
    - name: Install dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore --output ./output
  
    - name: Deploy
      uses: garygrossgarten/github-action-scp@release
      with:
        local: ./output
        remote: output
        host: '3.83.101.195'
        username: 'ubuntu'
        password: 'pak123lahore'
        
        
    - name: Copy to Deployment Folder
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: sudo rm -R '/var/www/project_output' && sudo cp -R '~/output' '/var/www/project_output' && sudo rm -R '~/output'
        host: '3.83.101.195'
        username: 'ubuntu'
        password: 'pak123lahore'

      
