name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    
    - name: Install dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore --output ./output
  
    - name: SSH Deploy
      shell: bash
      run: |
        sudo apt-get install sshpass
        tar -cvf ./output/tar.tar ./output.tar
        sshpass -p 'pak123lahore' scp ./output.tar ubuntu@3.83.101.195:/home/ubuntu/output.tar
        sshpass -p 'pak123lahore' ssh ubuntu@3.83.101.195 "sudo systemctl stop hello"
        sshpass -p 'pak123lahore' ssh ubuntu@3.83.101.195 "sudo rm -R '/var/www/project_output'"
        sshpass -p 'pak123lahore' ssh ubuntu@3.83.101.195 "sudo cp -R '/home/ubuntu/output' '/var/www/project_output' "
        sshpass -p 'pak123lahore' ssh ubuntu@3.83.101.195 "sudo rm -R '/home/ubuntu/output'"
        sshpass -p 'pak123lahore' ssh ubuntu@3.83.101.195 "sudo systemctl start hello"   
        
