name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
  
  

    - name: Setup SSH Keys and known_hosts
      run: |
            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            ssh-agent -a $SSH_AUTH_SOCK > /dev/null
            ssh-add - <<< "${{ secrets.DEPLOY_KEY }}"

    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    
    - name: Install dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore --output ./output
  
    - name: SSH Deploy
      shell: bash
      run: scp ./output ubuntu@52.255.173.7:~/output
        
    - name: Deploy
      uses: garygrossgarten/github-action-scp@release
      with:
        local: ./output
        remote: output
        host: '3.83.101.195'
        username: 'ubuntu'
        password: 'pak123lahore'
        
        
    - name: Copy to Deployment Folder
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: sudo systemctl stop hello 
        host: '3.83.101.195'
        username: 'ubuntu'
        password: 'pak123lahore'
        
    - name: Copy to Deployment Folder
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: sudo rm -R '/var/www/project_output' 
        host: '3.83.101.195'
        username: 'ubuntu'
        password: 'pak123lahore'
        
    - name: Copy to Deployment Folder
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: sudo cp -R '/home/ubuntu/output' '/var/www/project_output' 
        host: '3.83.101.195'
        username: 'ubuntu'
        password: 'pak123lahore'
        
    - name: Copy to Deployment Folder
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: sudo rm -R '/home/ubuntu/output'
        host: '3.83.101.195'
        username: 'ubuntu'
        password: 'pak123lahore'
        
    - name: Copy to Deployment Folder
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: sudo systemctl start hello
        host: '3.83.101.195'
        username: 'ubuntu'
        password: 'pak123lahore'
        
